[package]
name = "michie"
version = "0.2.1"
edition = "2021"
description = "An attribute macro that adds memoization to a function (pronounced /'mikÉª/)"
repository = "https://github.com/mobusoperandi/michie"
license = "MIT"
keywords = [
    "memoization",
    "memoisation",
    "memoize",
    "memoise",
    "cache",
]
categories = [
    "caching",
]
include = [
    "/README.md",
    "/src/**/*.rs",
    "/tests/**/*.rs",
    "/tests/compile_fail/*.stderr"
]

[workspace]
members = [
    "macro"
]

[dependencies]
michie-macro = { path = "macro", version = "0.2.0" }

[dev-dependencies]
cargo-make = "0.35.12"
conventional_commits_linter = "0.12.1"
itertools = "0.10.3"
trybuild = "^1.0.56"

[features]
