[package]
name = "caching"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
attribute-derive = "0.2.2"
proc-macro2 = "1.0.36"
quote = "1.0.16"
syn = { version = "1.0.86", features = ["full"] }

[dev-dependencies]
once_cell = "1.10.0"
trybuild = "1.0.56"

[features]
