[package]
name = "caching"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
attribute-derive = "0.2.2"
itertools = "0.10.3"
proc-macro-error = "1"
proc-macro2 = "1.0.36"
quote = "1"
syn = { version = "1.0.86", features = ["full"] }
