name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - uses: davidB/rust-cargo-make@v1
      - run: cargo make ci

