name: On push to master or pull request branch

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  cargo-make-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - uses: davidB/rust-cargo-make@v1
      - run: cargo make ci

