name: On push to master or pull_request

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  cargo-make-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo/
          key: ${{ runner.os }}-${{ hashFiles('executable-dev-dependency', 'Cargo.toml') }}
      - run: cargo install `cat executable-dev-dependency`
      - run: cargo make ci

