name: On push or pull_request

on:
  push: {}
  pull_request: {}

jobs:
  cargo-make-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for commit linting
      - run: rustup update
      - uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo/
          # cargo-run-bin refers to the following step
          key: ${{ runner.os }}_cargo-run-bin_${{ hashFiles('Cargo.toml', 'Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}_cargo-run-bin_
            ${{ runner.os }}_
      - run: cargo install cargo-run-bin
      - run: cargo bin makers ci
      - run: test -z `git ls-files --exclude-standard --others`

