name: On push to master or pull_request

on:
  push:
    branches: [master]
  pull_request: {}

env:
  RUSTFLAGS: --deny warnings

jobs:
  build:
    uses: ./.github/workflows/run-a-cargo-make-task.yml
    with:
      task: build
  test:
    needs: build
    uses: ./.github/workflows/run-a-cargo-make-task.yml
    with:
      task: test
  clippy:
    needs: build
    uses: ./.github/workflows/run-a-cargo-make-task.yml
    with:
      task: clippy
  doc:
    needs: build
    uses: ./.github/workflows/run-a-cargo-make-task.yml
    with:
      task: doc
  check_fmt:
    uses: ./.github/workflows/run-a-cargo-make-task.yml
    with:
      task: check_fmt
