name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: --deny warnings

    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt --check
      - name: Make documentation
        run: cargo doc
